name: Metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: skManux
          template: classic
          base: header, repositories
          config_timezone: Europe/Rome
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, shell
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_limit: 5
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_tweets: no
          plugin_music: no
